[package]
name = "libtailscale"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "libtailscale-sys"]

[dependencies]
libtailscale-sys = { path = "libtailscale-sys", version = "0.1.0" }
